name: Build Release Zip

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build and upload module
    runs-on: windows-latest
  
    steps:

    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies WCA
      run: dotnet restore UserInterface\UserInterface.csproj

    - name: Install dependencies Support.GenerateETWManifest
      run: dotnet restore ETWManifest\Support.GenerateETWManifest.csproj

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.3
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Build Debug
      run: msbuild UserInterface\UserInterface.csproj -property:Configuration=release /restore /t:Rebuild

    - name: Build ETW Manifest
      run: msbuild ETWManifest\Support.GenerateETWManifest.csproj -property:Configuration=release /restore /t:Rebuild

    - name: Create ZIP file
      run: |
        Add-Type -AssemblyName 'System.IO.Compression.FileSystem'
        [System.IO.Compression.ZipFile]::CreateFromDirectory("WCA\bin\release\net9.0-windows", "release.zip", [System.IO.Compression.CompressionLevel]::SmallestSize, $false)
        Write-Host "ZIP file created successfully at $zipFilePath"
      shell: pwsh

    - name: Upload Release Assets
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: release.zip
        asset_name: WindowsConfigurationAnalyzer_${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip